### ISSUE TITLE
Gives compilation error while migrating from swift 1.2 to 2.0

### ISSUE THREAD

**Issue by aadi007** [algolia/algoliasearch-client-swift#14]
I am using pod 'AlgoliaSearch-Client-Swift', '~> 1.4', all working well with swift 1.2. But as soon as I shifted to Xcode 7, it raised error in "Network.swift" and "Index.swift". Is anyone facing the same problem? or could anyone guide me to resolve this issue?

**Comment by redox** [comment]
We've just merged the `swift2` branch and will release a 2.0.0 very shortly on cocoapod (probably today). In the meantime, you can give a try to the `master` branch.

**Comment by aadi007** [comment]
Thanks for your reply! I just replaced the source folder's file with the latest one and worked for me. waiting for 2.0.0.

**Comment by narup** [comment]
Awesome! I was also looking for Swift 2.0 support

**Comment by redox** [comment]
We've just released the 2.0.0 (compatible with Swift 2) on cocoapods! Let us know how it goes :)
